### PR TITLE
enhanced subdir support for gitlab

### LINKED ISSUE #181: Subdirectory support results in error for GitLab projects
Subdirectory support works great for GitHub repos as seen [here](https://github.com/insightsengineering/tlg-catalog/blob/main/package/staged_dependencies.yaml#L2-L4), since GitHub follows a standard convention of having no hierarchy for its repositories and one can reference a package in a subdirectory using the $organization/repository/subdirectory$ pattern.

However, this imposes a problem for GitLab projects. GitLab supports a hierarchical structure for its repositories (projects).

So if we have a configuration that looks like:

```yaml
current_repo:
  repo: parent-group/sub-group/r.package
  host: https://gitlab.example.com
  host_type: gitlab
```

This results in the following error:

```ruby
Copying local dir /builds/parent-group/sub-group/r.package to cache dir ~/.staged.dependencies/packages_cache/local_parent-group_sub-group_r.package_1234567commit89123456sha
Error in check_dir_exists(repo_dir, "deps_info: ") : 
  deps_info: Directory ~/.staged.dependencies/packages_cache/local_parent-group_sub-group_r.package_1234567commit89123456sha/r.package does not exist.
Calls: <Anonymous> ... rec_checkout_internal_deps -> lapply -> get_yaml_deps_info -> check_dir_exists
```

## Proposed fix

Add support for an additional optional field in the `staged_dependencies.yaml` configuration that defines a new directive/key called `subdir` so that one can differentiate between a nested project in GitLab vs an actual subdirectory where the project is hosted. The default value of `subdir` should be `"."` and it should be an optional field.

Example:

```yaml
current_repo:
  repo: organization/awesome-project
  host: https://github.com
  host_type: github
  subdir: awesomePackage
```

### PR DESCRIPTION
**Pull request by pawelru**
I followed your suggestion of a new (optional) field `subdir` in the staged deps config.

Follow-up PRs:
- https://github.com/insightsengineering/tern/pull/1022
- https://github.com/insightsengineering/tlg-catalog/pull/94

### CODE REVIEW

File: R/git_tools.R [hunk 1]
```diff
@@ -14,15 +14,7 @@ get_repo_url <- function(repo, host) {
...
-  file.path(host, paste0(do.call(file.path, parse_git_ref(repo)[1:2]), ".git"))
-}
-
-parse_git_ref <- function(ref) {
-  list(
-    username = strsplit(ref, "/")[[1]][1],
-    repo = strsplit(ref, "/")[[1]][2],
-    subdir = paste0(strsplit(ref, "/")[[1]][-(1:2)], collapse = "/")
-  )
+  file.path(host, paste0(repo, ".git"))
```
Comment (cicdguy) [inline R/git_tools.R:17]: That's so much cleaner 😌

**Review by cicdguy — APPROVED** [review]
Thank you!

**Comment by pawelru** [comment]
It's passing so I am going to merge it now. Can you please execute the release of this as well as use this version in the workflows? Once done I will re-run my PRs and merge them
